name: commit
description: Commit and push any changes to branch specified
inputs:
  git-branch:
    description: Git branch to push changes to (if any)
    required: true
  github-token:
    description: GitHub personal access token with `repo` access to permit pushing changes to `git-branch`
    required: true

runs:
  using: composite
  steps:
    - name: Commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'chore: auto format and update docs' -a || echo 'Nothing to update'
        remote_repo="https://${GITHUB_ACTOR}:${{ inputs.github-token }}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:${{ inputs.git-branch }} || true
