name: pre-commit
description: Execute pre-commit for Terraform codebase
inputs:
  terraform-version:
    description: Terraform version supported for use in evaluation
    required: true
  terraform-docs-version:
    description: Version of terraform-docs to use when evaluating checks
    required: false
    default: v0.16.0
  args:
    description: Arguments to pass to pre-commit
    required: false
    default: '--all-files --color always --show-diff-on-failure'

runs:
  using: composite
  steps:
    - name: Install Terraform v${{ inputs.terraform-version }}
      shell: bash
      run: |
        curl -sSO https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip
        sudo unzip -qq terraform_${{ inputs.terraform-version }}_linux_amd64.zip terraform -d /usr/bin/
        rm terraform_${{ inputs.terraform-version }}_linux_amd64.zip 2> /dev/null

    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit

        curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${{ inputs.terraform-docs-version }}/terraform-docs-${{ inputs.terraform-docs-version }}-$(uname)-amd64.tar.gz
        sudo tar -xzf terraform-docs.tar.gz -C /usr/bin/ terraform-docs
        rm terraform-docs.tar.gz 2> /dev/null

        curl -sSL "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip
        sudo unzip -qq tflint.zip tflint -d /usr/bin/
        rm tflint.zip 2> /dev/null

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run ${{ inputs.args }}
