name: pre-commit
description: Execute pre-commit for Terraform codebase
inputs:
  terraform-version:
    description: Terraform version supported for use in evaluation
    required: true
  terraform-docs-version:
    description: Version of terraform-docs to use when evaluating checks
    required: false
    default: v0.16.0
  tflint-version:
    description: Version of tflint to use when evaluating checks
    required: false
    default: latest
  args:
    description: Arguments to pass to pre-commit
    required: false
    default: '--all-files --color always --show-diff-on-failure'
  install-hcledit:
    description: Install hcledit for pre-commit
    required: false
    default: 'false'
  hcledit-version:
    description: Version of hcledit to install when `install-hcledit` is true
    required: false
    default: 0.2.3

runs:
  using: composite
  steps:
    - name: Install Terraform v${{ inputs.terraform-version }}
      shell: bash
      run: |
        curl -sSO https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip
        sudo unzip -qq terraform_${{ inputs.terraform-version }}_linux_amd64.zip terraform -d /usr/bin/
        rm terraform_${{ inputs.terraform-version }}_linux_amd64.zip 2> /dev/null

    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit

        curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${{ inputs.terraform-docs-version }}/terraform-docs-${{ inputs.terraform-docs-version }}-$(uname)-amd64.tar.gz
        sudo tar -xzf terraform-docs.tar.gz -C /usr/bin/ terraform-docs
        rm terraform-docs.tar.gz 2> /dev/null

        if [[ "${{ inputs.tflint-version }}" == "latest" ]]; then
          curl -sSL "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip
        else
          curl -sSLo ./tflint.zip https://github.com/terraform-linters/tflint/releases/download/${{ inputs.tflint-version }}/tflint_linux_amd64.zip
        fi
        sudo unzip -qq tflint.zip tflint -d /usr/bin/
        rm tflint.zip 2> /dev/null

        if [[ "${{ inputs.install-hcledit }}" == "true" ]]; then
          curl -sSLo ./hcledit.tar.gz https://github.com/minamijoyo/hcledit/releases/download/v${{ inputs.hcledit-version }}/hcledit_${{ inputs.hcledit-version }}_$(uname)_amd64.tar.gz
          sudo tar -xzf hcledit.tar.gz -C /usr/bin/ hcledit
          rm hcledit.tar.gz 2> /dev/null
        fi

        curl -sSL "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E "https://.+?_linux_amd64.tar.gz")" > tfsec.tar.gz
        sudo tar -xzf tfsec.tar.gz -C /usr/bin/ tfsec tfsec-checkgen

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run ${{ inputs.args }}
