name: directories
description: Collects list of Terraform directories
outputs:
  directories:
    description: Array of directories that contain a `versions.tf` file
    value: ${{ steps.search.outputs.directories }}

runs:
  using: composite
  steps:
    - name: Get Terraform directories for evaluation
      shell: bash
      id: search
      run: |
        ls -la
        DIRS=$(python ./directories/directories.py)
        echo "directories=$DIRS" >> $GITHUB_OUTPUT
